server:
  port: 8081


spring:
  application:
    name: command-service

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5434/command-db
    username: command-user
    password: command-password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

